version: '3.1'
services:
  appnetflix:
    image: wlopezob/minetflix:v1
    container_name: container_minetflix
    restart: always
    ports:
      - 8080:80
    networks:
      - net-minetflix
    #volumes:
      #- ./package.json:/usr/src/app/
networks:
  net-minetflix: